// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://wrjqheztddmazlifbzbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyanFoZXp0ZGRtYXpsaWZiemJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1MzAzMDgsImV4cCI6MjA4NTEwNjMwOH0.l1EojJhtPIrMqy5FUkLQaPj-Ccpt0fKbV0ByJx2JQuU";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
